### ISSUE TITLE
"Is Mounted" not working

### ISSUE THREAD

**Issue by ChekistNSK** [Geigerkind/ModifiedPowerAurasTBC#22]
1) Create as warlock new Aura with name of the buff "Soul Link"
2) Check "Is Mounted" as red cross
3) Aura activated as mounted / unmounted ...

**Comment by Arcitec** [comment]
I found out why this isn't working.

In `zzzModifiedPowerAuras/Conditions.lua`, there is a function named `MPOWA:IsMounted()` (which is only called from 1 place in `Auras.lua`). It does a lot of complicated work:

```lua
function MPOWA:IsMounted()
	MPowa_Tooltip:SetOwner(UIParent, "ANCHOR_NONE")
	for i=0,40 do
		MPowa_Tooltip:ClearLines()
		MPowa_Tooltip:SetPlayerBuff(GetPlayerBuff(i, "HELPFUL|PASSIVE"))
		local desc = MPowa_TooltipTextLeft2:GetText()
		if (not desc) then break end
		if strfind(desc, MPOWA_SCRIPT_MOUNT_100) or strfind(desc, MPOWA_SCRIPT_MOUNT_60) then
			self.mounted = true
			return
		end
	end
	self.mounted = false
end
```

The strings it searches for is:

```lua
zzzModifiedPowerAuras/localization/enUs.lua
91:MPOWA_SCRIPT_MOUNT_100 = "Increases speed by 100"
92:MPOWA_SCRIPT_MOUNT_60 = "Increases speed by 60"
```

So basically it does some weird "scan all buffs to look for one with the text "increases speed by 60/100".

Some problems:

1. What about other languages? This only works for English (and the German translation included too).
2. What about Outlands mounts? This doesn't work for them. They are faster than 60/100. ;-)

But there's a solution, @Geigerkind ! :-)

WoW's built-in TBC API: `IsMounted()`. It's true if mounted, false otherwise. ;-)

So all of this complicated tooltip-scan code can be replaced with just the TBC built-in API instead.

http://wowwiki.wikia.com/wiki/API_IsMounted

**Comment by tdymel** [comment]
Fixed thanks!
